### ISSUE TITLE
wifi and bluetooth

### ISSUE THREAD

**Issue by danielnilsson9** [jumpnow/meta-rpi#1]
Hi

This is not really an issue with your code but I'm reaching out to you in hope that you could help me. I have spent an ridiculous amount of time trying to build a minimal image with working wifi and bluetooth for rpi3  with yocto.

You said wifi worked with this layer so I have basically tried to copy your setup.

I have taken your:
recipes-bsp/bootfiles
recipes-bsp
recipes-kernel

And my image is identical to your console-image.bb. My local.conf is pretty much identical to your sample too.

The build goes fine and I get a bootable image but whatever I do I can not get the wifi driver to load.
Nothing related to brcmfmac shows up in dmesg and its not loaded since it does not show up when running lsmod.

The driver files are clearly there under /lib/firmware/brcm however.

If i plug in a wifi usb dongle it works fine too...

I have tried building your meta-rpi console-image too and it doesn't work either. If I however download your prebuilt x11 image it works fine.

I'm hoping you may have some idea whats going on here.

Thank you for reading,
Daniel

**Comment by scottellis** [comment]
4.5 kernel? That the only one I tried the RPi3 wifi.

Do you have these kernel modules?

root@rpi3:/lib/modules/4.5.0/kernel/drivers/net/wireless/broadcom# ls
b43  b43legacy  brcm80211


root@rpi3:/lib/modules/4.5.0/kernel/drivers/net/wireless/broadcom# ls -l
total 12
drwxr-xr-x 2 root root 4096 Mar 26 09:11 b43
drwxr-xr-x 2 root root 4096 Mar 26 09:11 b43legacy
drwxr-xr-x 4 root root 4096 Mar 26 09:21 brcm80211


root@rpi3:/lib/modules/4.5.0/kernel/drivers/net/wireless/broadcom# ls -l brcm80211/
total 8
drwxr-xr-x 2 root root 4096 Mar 26 09:11 brcmfmac
drwxr-xr-x 2 root root 4096 Mar 26 09:11 brcmutil


root@rpi3:/lib/modules/4.5.0/kernel/drivers/net/wireless/broadcom# ls -l brcm80211/brcmfmac/
total 288
-rw-r--r-- 1 root root 291032 Mar 26 09:11 brcmfmac.ko


root@rpi3:/lib/modules/4.5.0/kernel/drivers/net/wireless/broadcom# ls -l brcm80211/brcmutil/
total 16
-rw-r--r-- 1 root root 14988 Mar 26 09:11 brcmutil.ko




"Daniel Nilsson" <notifications@github.com> said:

**Comment by danielnilsson9** [comment]
4.1.20

But I found the problem finally. bcm2710-rpi3-b.dtb weren't being placed in boot partition so it booted as a rpi2. I was using the rpi-sdimg generated by meta-raspberrypi I think.

Haven't got bluetooth to work yet though, device not detected by hciconfig -a but I guess its something simple, wifi works now at least.

Thank you anyway!
