### ISSUE TITLE
How to build with internal BT enabled for RPI3

### ISSUE THREAD

**Issue by mark2b** [jumpnow/meta-rpi#3]
How can I build image with internal BT enabled ?
ENABLE_RPI3_SERIAL_CONSOLE= "0" in the local.conf doesn't help

**Comment by scottellis** [comment]
Remove this line from your local.conf

  ENABLE_RPI3_SERIAL_CONSOLE = "1"

or just delete / comment this line from your config.txt

## Disable RPi3 bluetooth to enable serial console on UART0
dtoverlay=pi3-disable-bt

That's so the kernel driver can talk to the BT radio using
the UART.

Then add bluez5 to your IMAGE_INSTALL to get some userland tools.

I think that's all you should need. 

The kernel in meta-rpi uses the same kernel and kernel config
(bcm2709_defconfig) that Raspbian uses with one extra ADC driver
enabled in my kernels.

I haven't tried any of this though.


"Mark Berner" <notifications@github.com> said:

**Comment by mark2b** [comment]
did exactly you said:
but hciconfig -a returns empty output
There is no hci0

**Comment by scottellis** [comment]
Take a look at what raspbian is doing.

The two systemd services that are applicable are

bluetooth.service
hciuart.service

===
pi@raspberrypi:/lib/systemd/system $ cat bluetooth.service
[Unit]
Description=Bluetooth service
Documentation=man:bluetoothd(8)

[Service]
Type=dbus
BusName=org.bluez
ExecStart=/usr/lib/bluetooth/bluetoothd
NotifyAccess=main
#WatchdogSec=10
#Restart=on-failure
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE
LimitNPROC=1

[Install]
WantedBy=bluetooth.target
Alias=dbus-org.bluez.service
===

===
pi@raspberrypi:/lib/systemd/system $ cat hciuart.service
[Unit]
Description=Configure Bluetooth Modems connected by UART
ConditionPathIsDirectory=/proc/device-tree/soc/gpio@7e200000/bt_pins
Before=bluetooth.service
After=dev-serial1.device

[Service]
Type=forking
ExecStart=/usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow -

[Install]
WantedBy=multi-user.target
===

So the first thing I would try is running this manually

  /usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow -

then see if you have hciconfig -a shows you anything.

I might get a chance to look at this later today.



"Mark Berner" <notifications@github.com> said:

**Comment by scottellis** [comment]
/dev/serial1 is just a link to /dev/ttyAMA0

From raspbian

pi@raspberrypi:~ $ ls -l /dev/serial1
lrwxrwxrwx 1 root root 7 Sep 23 04:02 /dev/serial1 -> ttyAMA0



"Mark Berner" <notifications@github.com> said:

**Comment by mark2b** [comment]
/usr/bin/hciattach /dev/serial1 bcm43xx 921600 noflow -
**bcm43xx_init
Initialization timed out**

**Comment by scottellis** [comment]
You probably don't have a /dev/serial1 unless you added a
udev rule or created a link manually.

Try /dev/ttyAMA0, that's the UART the BT radio is attached to.


"Mark Berner" <notifications@github.com> said:

**Comment by scottellis** [comment]
Eliminate /dev/ttyAMA0 from being used as a console.

1) Remove the console= part of cmdline.txt
2) Remove the AMA0 line from /etc/inittab

Reboot

root@rpibt:~# modprobe hci_uart

root@rpibt:~# /usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
bcm43xx_init
Cannot open directory '/etc/firmware': No such file or directory
Patch not found, continue anyway
Set Controller UART speed to 921600 bit/s
Device setup complete

root@rpibt:~# hciconfig -a
hci0:   Type: BR/EDR  Bus: UART
        BD Address: AA:AA:AA:AA:AA:AA  ACL MTU: 1021:8  SCO MTU: 64:1
        DOWN
        RX bytes:668 acl:0 sco:0 events:34 errors:0
        TX bytes:423 acl:0 sco:0 commands:34 errors:0
        Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH SNIFF
        Link mode: SLAVE ACCEPT


That's all I have time for today.

"Mark Berner" <notifications@github.com> said:

**Comment by mark2b** [comment]
It was solved only after removing meta-rpi from belayers.com, but using console-image.bb (after removing some unnecessary for me dependencies)
